# Generated by Django 5.2 on 2025-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('marketing', models.CharField(blank=True, max_length=100, null=True)),
                ('orcamento_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alinhamento_orgao_controle', models.TextField(blank=True, null=True)),
                ('contratacoes', models.TextField(blank=True, null=True)),
                ('estruturas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
