# Generated by Django 5.2 on 2025-04-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_evento', '0002_evento_equipamento_evento_fornecedores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagem do Evento'),
        ),
    ]
