# Generated by Django 5.2 on 2025-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_evento', '0003_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='responsavel',
            field=models.CharField(choices=[('Secretaria de Turismo', 'Secretaria de Turismo'), ('Secretaria de Cultura', 'Secretaria de Cultura')], max_length=100, verbose_name='Responsável'),
        ),
    ]
